### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by picks44** [Happyr/LinkedInBundle#7]
Hi there,

Sorry I do'nt get it in your doc : do we have to do `composer require php-http/curl-client guzzlehttp/psr7 php-http/message happyr/linkedin-bundle` AND `composer require php-http/httplug-bundle` ? 
Or just the first one ?

**Comment by Nyholm** [comment]
Just the first one. That includes `happyr/linkedin-bundle`

**Comment by Nyholm** [comment]
See new suggestions for instructions at #8. What do you think?

**Comment by picks44** [comment]
@Nyholm nice! Much understandable :) So `httplug-bundle` is just for debugging right ?

**Comment by Nyholm** [comment]
Pretty much. It will also help you register services for 

```yaml
happyr_linkedin:
  http_client: 'httplug.client' 
  http_message_factory: 'httplug.message_factory' 
```

But it is HTTPlug bundle optional (but awesome) =)
